%% -*- coding: utf-8 -*-
%% Automatically generated, do not edit
%% Generated by gpb_compile version 3.26.4

-ifndef(riak_core_pb).
-define(riak_core_pb, true).

-define(riak_core_pb_gpb_version, "3.26.4").

-ifndef('RIAKOBJECT_PB_PB_H').
-define('RIAKOBJECT_PB_PB_H', true).
-record(riakobject_pb,
        {bucket                 :: binary(),        % = 1
         key                    :: binary(),        % = 2
         val                    :: binary()         % = 3
        }).
-endif.

-endif.
