name: Erlang CI

on:
  push

jobs:

  build:

    runs-on: ubuntu-latest

    container:
      image: erlang:22.3.3

    steps:
      - uses: actions/checkout@v2
      - name: Compile
        run: ./rebar3 compile
      - name: Run xref and dialyzer
        run: rebar3 do xref, dialyzer
      - name: Eunit
        run: GITHUBACTIONS=true rebar3 eunit
