name: Erlang CI

on:
  push

jobs:

  build:

    runs-on: ubuntu-latest

    container:
      image: erlang:22.3.3

    steps:
    - uses: actions/checkout@v2
    - name: Compile
      run: ./rebar3 compile
    - name: Run tests
      run: ./rebar3 do xref, eunit --module=riak_kv_vnode_status_mgr
